# Kubernetes Deployment for OpenManus-Youtu API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmanus-youtu-api
  namespace: openmanus-youtu
  labels:
    app: openmanus-youtu-api
    component: api
    version: "1.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmanus-youtu-api
  template:
    metadata:
      labels:
        app: openmanus-youtu-api
        component: api
        version: "1.0.0"
    spec:
      containers:
      - name: api
        image: openmanus-youtu/framework:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: LOG_LEVEL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openmanus-youtu-secrets
              key: postgres-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: openmanus-youtu-config
              key: REDIS_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-youtu-secrets
              key: jwt-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: data
          mountPath: /app/data
      volumes:
      - name: logs
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: openmanus-youtu-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# Kubernetes Service for OpenManus-Youtu API
apiVersion: v1
kind: Service
metadata:
  name: openmanus-youtu-api-service
  namespace: openmanus-youtu
  labels:
    app: openmanus-youtu-api
spec:
  selector:
    app: openmanus-youtu-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP